#!/bin/bash
#Menu

echo -e "* 1         : ดูรายการต่างมีดังนี้นะครับพี่"
echo -e "* 2         : สร้างบัญชี SSH & OpenVPN"
echo -e "* 3         : สร้างบัญชีทดลอง SSH & OpenVPN"
echo -e "* 4         : ลบรายชื่อ SSH & OPEN VPN"
echo -e "* 5         : แสดงรายชื่อที่ออนไลน์ SSH & OPEN VPN"
echo -e "* 6         : แสดงรายชื่อทั้งหมด SSH & OpenVPN"
echo -e "* 7         : รีระบบทั้งหมด restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "* 8         : รีบูทระบบ VPS"
echo -e "* 9         : ทดสอบเทสสปีด VPS"
echo -e "* 10        : ดูการใช้ RAM ของเซิร์ฟเวอร์"
echo -e "* 11        : ดูรายชื่อออนไลน์ทั้งหมดและไม่ออนไลน์"
echo -e "* about     : ดูรายละเอียดการติดตั้งของระบบ"
echo -e "* exit      : ออกจากระบบ keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e "            สนใจติด Facebook: nipon kaewtes ,ID Line: nipon24082535"
echo -e "            เบอร์โทรศพท์ 0940749370-โชค"
echo -e ""
